on: [push]

jobs:
  build:
    name: My First Action!
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: testing in progress
        run: |
          echo "My very first Github Actions!"
