on: [push]

jobs:
  build: 
  name: My First Action!
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - name: Write a multi-line message
    run: |
      echo My very first Github Actions!
